name: Dart CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Run tests
        run: |
          dart test test/ajout_test.dart
          dart test test/urgence_test.dart
          dart test test/completion_test.dart
          dart test test/suppression_test.dart
          dart test test/tri_test.dart
